export const priceData = [
  {
    id: '1',
    title: 'Free',
    price: 0,
    users: 'Single',
    storage: '5GB',
    unlimitedPublicProjects: true,
    communityAccess: false,
    unlimitedPrivateProjects: false,
    phoneSupport: false,
    subDomain: false,
    monthlyStatusReport: false,
  },
  {
    id: '2',
    title: 'Plus Tier',
    price: 9,
    users: '5',
    storage: '50GB',
    unlimitedPublicProjects: true,
    communityAccess: true,
    unlimitedPrivateProjects: true,
    phoneSupport: true,
    subDomain: true,
    monthlyStatusReport: false,
  },
  {
    id: '3',
    title: 'Pro',
    price: 49,
    users: 'Unlimited',
    storage: '150GB',
    unlimitedPublicProjects: true,
    communityAccess: true,
    unlimitedPrivateProjects: true,
    phoneSupport: true,
    subDomain: true,
    monthlyStatusReport: true,
  },
];

